services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./.docker/volumes/postgresql/data/:/var/lib/postgresql/data/
  backend:
    container_name: backend
    image: golang:1.23.0-alpine
    working_dir: /app
    command: tail -f /dev/null
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "4431:443"
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: node:20-alpine
    working_dir: /app
    command: "sleep infinity"
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
    ports:
      - "80:3000"
      - "443:3000"

volumes:
  go-cache:
