services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/volumes/postgresql/data/:/var/lib/postgresql/data/
  backend:
    container_name: backend
    image: golang:1.23.0-alpine
    working_dir: /app
    command: tail -f /dev/null
    env_file:
      - .env
    # environment:
    #   ENVIRONMENT: ${ENVIRONMENT}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   HOSTS: ${HOSTS}
    #   TLS_CERTIFICATES_DIR: ${TLS_CERTIFICATES_DIR}
    ports:
      - "8080:80"
      - "4431:443"
    volumes:
      - .:/app
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: node:20-alpine
    working_dir: /app
    command: "sleep infinity"
    volumes:
      - ./frontend:/app
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "80:3000"
