// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbs

import (
	"database/sql"
)

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
